# Generated by Django 5.1.5 on 2025-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenence'), ('o', 'On Loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', max_length=1),
        ),
    ]
